#!/usr/bin/env python3
"""Aggregate harvested Wikipedia citations into a ranked acquisition list.

  uv run --no-project lit/wikipedia/aggregate.py

Reads harvest/*.json (produced by the /wikipedia skill's `references` subcommand)
and writes ranked.md plus ranked.csv.

Ranking is by **how many distinct nexus articles cite the work**. A monograph
cited by Gandhara, Kushan Empire and Silk Road alike is load-bearing for the
contact-zone literature in a way a single-article citation is not. This is a
crude centrality measure and nothing more: it reflects what Wikipedia editors
reached for, not what the field considers authoritative.
"""

from __future__ import annotations

import csv
import json
import re
from collections import defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent
HARVEST = HERE / "harvest"


def norm(s: str | None) -> str:
    if not s:
        return ""
    s = re.sub(r"\{\{.*?\}\}|<[^>]+>", "", s)
    return re.sub(r"[^a-z0-9]+", " ", s.lower()).strip()


def key(c: dict) -> str | None:
    """Identity of a work: ISBN if present, else normalised author+title."""
    if c.get("isbn"):
        return "isbn:" + re.sub(r"[^0-9xX]", "", c["isbn"])
    if c.get("doi"):
        return "doi:" + c["doi"].lower()
    t = norm(c.get("title"))
    a = norm((c.get("authors") or [""])[0])
    return f"t:{a}|{t}" if t else None


def main() -> None:
    works: dict[str, dict] = {}
    sources: dict[str, set[str]] = defaultdict(set)

    for f in sorted(HARVEST.glob("*.json")):
        d = json.loads(f.read_text(encoding="utf-8"))
        art = d.get("title")
        if not art:
            continue
        for c in d.get("citations", []):
            k = key(c)
            if not k:
                continue
            sources[k].add(art)
            cur = works.get(k)
            # Keep the richest record seen for a work: citations of the same book
            # vary in completeness between articles.
            if cur is None or sum(bool(v) for v in c.values()) > sum(
                bool(v) for v in cur.values()
            ):
                works[k] = c

    rows = []
    for k, c in works.items():
        ident = c.get("isbn") or c.get("doi") or c.get("jstor") or c.get("issn") or ""
        rows.append(
            {
                "n_articles": len(sources[k]),
                "articles": "; ".join(sorted(sources[k])),
                "authors": "; ".join(c.get("authors") or []),
                "title": (c.get("title") or "").strip(),
                "work": c.get("work") or "",
                "publisher": c.get("publisher") or "",
                "year": c.get("year") or "",
                "identifier": ident,
                "url": c.get("url") or "",
                "unlinked": bool(ident and not c.get("url")),
                "type": c.get("type") or "",
            }
        )

    rows.sort(key=lambda r: (-r["n_articles"], -len(r["identifier"]), r["title"]))

    with (HERE / "ranked.csv").open("w", newline="", encoding="utf-8") as fh:
        # csv defaults to CRLF; this file is committed, so keep it LF.
        w = csv.DictWriter(fh, fieldnames=list(rows[0]), lineterminator="\n")
        w.writeheader()
        w.writerows(rows)

    multi = [r for r in rows if r["n_articles"] > 1]
    unlinked = [r for r in rows if r["unlinked"]]

    lines = [
        "# Wikipedia citation harvest — ranked",
        "",
        "Generated by `aggregate.py` from `harvest/*.json`. **Candidates, not sources.**",
        "Nothing here has been verified; everything enters `resources.md` as `#e/unverified`",
        "until traced to the work itself (`resources.md` §17.1).",
        "",
        f"- {len(rows)} distinct works from {len(list(HARVEST.glob('*.json')))} articles",
        f"- {len(multi)} cited by more than one article",
        f"- {len(unlinked)} carry a durable identifier but no URL — the class no index"
        " this project can search will return",
        "",
        "Ranking is by number of citing articles: a crude centrality measure that reflects",
        "what Wikipedia editors reached for, not what the field considers authoritative.",
        "",
        "## Cited by more than one nexus article",
        "",
        "| n | authors | title | year | id | articles |",
        "|---|---|---|---|---|---|",
    ]
    for r in multi[:60]:
        t = r["title"][:78].replace("|", "/")
        a = r["authors"][:44].replace("|", "/") or "—"
        lines.append(
            f"| {r['n_articles']} | {a} | {t} | {r['year'][:12]} | "
            f"{r['identifier'][:22] or '—'} | {r['articles'][:60]} |"
        )
    (HERE / "ranked.md").write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"{len(rows)} works | {len(multi)} multi-article | {len(unlinked)} identified-but-unlinked")
    print("wrote ranked.csv, ranked.md")
    print()
    for r in multi[:18]:
        print(f"  [{r['n_articles']}] {(r['authors'] or '—')[:34]:34} {r['title'][:60]}")


if __name__ == "__main__":
    main()
